version: 0.2

env:
  parameter-store:
    NPM_TOKEN: /ottokruse/npm/token

phases:
  install:
    commands:
      - npm it
  build:
    commands:
      - npm run build
      - mkdir smoke-test && cd smoke-test &&
        npm init -y && npm i ../ &&
        node -e "const importTest = require('crypto-secure-random-digit');" &&
        cd - && echo " >> Import test OK"
  post_build:
    commands:
      - NPM_VERSION=$(npm view crypto-secure-random-digit version) &&
        LOCAL_VERSION=$(node get-local-version.js) &&
        if [ ${LOCAL_VERSION} != ${NPM_VERSION} ]; then
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc;
            npm publish;
        fi;
cache:
  paths:
    - 'node_modules/**/*'
